export const CART = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
    ADD_TO_PRODUCTS: "ADD_TO_PRODUCTS",
    GET_USER_CART: "GET_USER_CART",
    PENDING_STATE: "PENDING_STATE",
    GET_ERROR_MSG: "GET_ERROR_MSG",
};